runtime: custom
api_version: '1.0'
env: flex
resources:
  cpu: 1
  memory_gb: 2
threadsafe: true
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3
  cpu_utilization:
    target_utilization: 0.5
